
ALTER TABLE public.companies
  ADD COLUMN IF NOT EXISTS rccm TEXT,
  ADD COLUMN IF NOT EXISTS nif TEXT,
  ADD COLUMN IF NOT EXISTS website TEXT,
  ADD COLUMN IF NOT EXISTS currency TEXT NOT NULL DEFAULT 'FCFA';

ALTER TABLE public.clients
  ADD COLUMN IF NOT EXISTS nif TEXT;
