// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ltwpsuhpqhkfwnsojvej.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx0d3BzdWhwcWhrZnduc29qdmVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5Mzg5NjAsImV4cCI6MjA2NDUxNDk2MH0.KHsk2-XiwXxZDBBLRoJicMA8DtP-Tkj4aG1znCz3umU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);